[package]
name = "garbazan-roulette"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
uuid = { version = "1.15.1", features = ["v4"] }
serde = "1.0.218"
serde_json = "1.0.140"
lazy_static = "1.5.0"
rocket_cors = "0.6.0"
mime = "0.3.17"